/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Status, } from "./global/interfaces/charts";
import { Variables, } from "./global/interfaces/jeep-linechart";
export namespace Components {
    interface JeepLinechart {
        "animation": boolean;
        "cborder": boolean;
        "ctitle": string;
        "data": string;
        "delay": string;
        "getCssProperties": () => Promise<Variables>;
        "getStatus": () => Promise<Status>;
        "init": () => Promise<void>;
        "renderChart": () => Promise<void>;
        "subtitle": string;
        "xtitle": string;
        "ytitle": string;
    }
}
declare global {
    interface HTMLJeepLinechartElement extends Components.JeepLinechart, HTMLStencilElement {
    }
    var HTMLJeepLinechartElement: {
        prototype: HTMLJeepLinechartElement;
        new (): HTMLJeepLinechartElement;
    };
    interface HTMLElementTagNameMap {
        "jeep-linechart": HTMLJeepLinechartElement;
    }
}
declare namespace LocalJSX {
    interface JeepLinechart {
        "animation"?: boolean;
        "cborder"?: boolean;
        "ctitle"?: string;
        "data"?: string;
        "delay"?: string;
        "onJeepLinechartReady"?: (event: CustomEvent<any>) => void;
        "subtitle"?: string;
        "xtitle"?: string;
        "ytitle"?: string;
    }
    interface IntrinsicElements {
        "jeep-linechart": JeepLinechart;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "jeep-linechart": LocalJSX.JeepLinechart & JSXBase.HTMLAttributes<HTMLJeepLinechartElement>;
        }
    }
}
